services:
  kenespartadev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kenespartadev
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge